---

- name: "Ansible lib Debug"
  vars:
    msg: |
      ansible_architecture [ {{ ansible_architecture }} ]
      ansible_os_family [ {{ ansible_os_family }} ]
      ansible_distribution [ {{ ansible_distribution }} ]
      ansible_distribution_major_version [ {{ ansible_distribution_major_version }} ]
      ansible_distribution_version [ {{ ansible_distribution_version }} ]
      ansible_distribution_release [ {{ ansible_distribution_release }} ]

  debug:
    msg: "{{ msg.split('\n') }}"

# EOF
...
